### ISSUE TITLE
What's the lowest version of golang this requests?

### ISSUE THREAD

**Issue by meeeo** [dsnet/udptunnel#3]
Is golang-1.7 and golang-1.6 satisfied enough?
Thank you.

**Comment by meeeo** [comment]
It seems like 1.7 is the answer.

**Comment by dsnet** [comment]
Go1.7 introduces the `context` package, which is heavily used by this package, so Go1.7. However, I don't plan on intentionally supporting anything other than the latest released version of Go. This is a standalone program, and not a package that others depend on. Having that requirement seems reasonable.
