### ISSUE TITLE
There's already some package called udptunnel in APT 

### ISSUE THREAD

**Issue by meeeo** [dsnet/udptunnel#4]
But obviously different usage.
Maybe you could change to another name.
![img_7585](https://user-images.githubusercontent.com/5188710/36969577-dc862ce8-20a0-11e8-8721-7edf8b7699ff.JPG)

**Comment by dsnet** [comment]
Hi, I wrote this program for person use and have no intention of ever adding it to the apt repositories. In fact, I prefer that it never happen as I do not have the bandwidth to provide support for this repository beyond fixing issues for my personal needs.
