### ISSUE TITLE
how to bind specific tcp port on clinet side ?

### ISSUE THREAD

**Issue by prxpostern** [dsnet/udptunnel#9]
hi . is there a way to bind tcp port on client side in lictening mode ? so i will be able to forward my tcp packets over that specific binded port , from intern to destination server. 

thanks

i mean like ssh local port forwarding.

**Comment by dsnet** [comment]
There's no support for that. This entire project exists to work around a faulty router that kept dropping persistent TCP connections.

If you want a point-to-point VPN, I highly recommend looking into https://tailscale.com/
